# @package _global_

n_workers: 4
batch_size: 1024
max_augm_epochs: 0  # AUGMENTATIONS DISABLED!
augm_prob: 0.7
n_params: 15
train_data_ratio: 1.0

preprocessing:
  _target_: mcmlnet.training.data_loading.preprocessing.PreProcessor
  _recursive_: False

  dataset_name: raw/base_physio_and_physical_simulations/physiological_training_100M_photons_1M_samples.parquet
  n_wavelengths: ${n_wavelengths}
  refl_range: None
  param_range: z-score
  log: True
  log_intensity: False
  kfolds: 5
  fold: 0
  is_or_make_physical: True
  n_pca_comp: ${n_comp}
  batch_size: 100000

data_module:
  _target_: mcmlnet.training.data_loading.data_module.DataModule
  _recursive_: False

dataset:
  _target_: mcmlnet.training.data_loading.datasets.DatasetMCPred
  _recursive_: False

  n_wavelengths: ${n_wavelengths}
  n_params: ${n_params}
  thick_deepest_layer: True

additional_scaling:
  dataset_loader:
    _target_: mcmlnet.utils.loading.SimulationDataLoader
    _recursive_: false
    n_layers: 3
    n_physio_params: 8
    n_physical_params: 5
    is_physical: false
  data: raw/base_physio_and_physical_simulations/physiological_training_100M_photons_5M_samples.parquet
  n_wavelengths: ${n_wavelengths}

input_augmentations:
  _recursive_: True

  noise:
    _target_: mcmlnet.training.data_loading.data_augmentation_classes.NoiseAdditionWithExponentialDecay
    snr: 50
    batches_per_epoch: 5000
    max_epochs: ${max_augm_epochs}
    p: ${augm_prob}
    clipping: True

output_augmentations:
  _recursive_: True

  noise:
    _target_: mcmlnet.training.data_loading.data_augmentation_classes.NoiseAdditionWithExponentialDecay
    snr: 50
    batches_per_epoch: 5000
    max_epochs: ${max_augm_epochs}
    p: ${augm_prob}
    clipping: True
